name: Scraper

on:
  schedule:
    - cron: '0 3 * * *' # Runs at 3am UTC/11pm EST
  workflow_dispatch:      # Manual Trigger

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    env:
      EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
    steps: 
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt
      - run: python main.py
