name: Scraper

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
on:
  schedule:
    - cron: '0 3 * * *' # Runs at 3am UTC/11pm EST
  workflow_dispatch:      # Manual Trigger

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt
      - run: python main.py
